# markdown preview
# - install yarn
# - cd ~/.vim/bundle/markdown-preview.nvim/app
# - yarn install
[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'sh -c "cd app && npx --yes yarn install"'
