# base
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

# file
[[plugins]]
repo = 'Townk/vim-autoclose'

# status
[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo =  'scrooloose/syntastic'

# color schemes
[[plugins]]
repo = 'jtai/vim-womprat'

# git operation
[[plugins]]
repo = 'tpope/vim-fugitive'

# show git
[[plugins]]
repo = 'airblade/vim-gitgutter'

# spell check
[[plugins]]
repo = 'kamykn/spelunker.vim'

# color code
[[plugins]]
repo = 'gorodinskiy/vim-coloresque'

# calc
[[plugins]]
repo = 'theniceboy/vim-calc'
